/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sci-fi_female_soldier_lowpoly.glb 
Author: Fraser Gray (https://sketchfab.com/FraserG)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-female-soldier-lowpoly-6d23775b6f1447a39b70deeb29d9b959
Title: Sci-fi Female Soldier (Lowpoly)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FemaleSoldier(props) {
  const { nodes, materials } = useGLTF('/models/sci-fi_female_soldier_lowpoly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/sci-fi_female_soldier_lowpoly.glb')
